apiVersion:  apps/v1beta1
kind: Deployment
metadata:
  name: minecraft
  namespace: azure
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: holdocker2018.azurecr.io/minecraft:0.1.0
        ports:
        - containerPort: 25565
      imagePullSecrets:
      - name: azureregistry